services:
  postgres:
    image: 'postgres:latest'
    ports:
      - '5432'
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_DB=digital_account'
