spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/digital_account
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  jackson:
    default-property-inclusion: non-null
