CREATE TABLE
    customer
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(100)                            NOT NULL,
    cpf      VARCHAR(15)                             NOT NULL,
    email    VARCHAR(100) UNIQUE                     NOT NULL,
    password TEXT UNIQUE                             NOT NULL,
    CONSTRAINT pk_customer PRIMARY KEY (id)
);

CREATE TABLE
    account
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    account_type VARCHAR(15)                             NOT NULL,
    balance      DECIMAL DEFAULT 0.0                     NOT NULL,
    customer_id  BIGINT                                  NOT NULL,
    CONSTRAINT pk_account PRIMARY KEY (id),
    CONSTRAINT FK_ACCOUNT_ON_CUSTOMER FOREIGN KEY (customer_id) REFERENCES customer (id)
);

CREATE TABLE
    transaction
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type       VARCHAR(15)                             NOT NULL,
    amount     DECIMAL                                 NOT NULL,
    created_at TIMESTAMP DEFAULT NOW()                 NOT NULL,
    account_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_transaction PRIMARY KEY (id),
    CONSTRAINT FK_TRANSACTION_ON_ACCOUNT FOREIGN KEY (account_id) REFERENCES account (id)
);
